global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'express-api'
    static_configs:
      - targets: ['express-api:3001']
    metrics_path: '/metrics'

  - job_name: 'influx'
    static_configs:
      - targets: ['influxdb:8086']
    
